### ISSUE TITLE
Undefined index when going through checkout in WP e-commerce plugin

### ISSUE THREAD

**Issue by martisj** [DIBS-Payment-Services/Ecommerce#5]
Getting these messages:
```
[09-Feb-2016 21:43:15 UTC] PHP Notice:  Undefined index:  in dibspw.php on line 326
[09-Feb-2016 21:43:15 UTC] PHP Notice:  Undefined index:  in dibspw.php on line 327
[09-Feb-2016 21:43:15 UTC] PHP Notice:  Undefined index:  in dibspw.php on line 328
[09-Feb-2016 21:43:15 UTC] PHP Notice:  Undefined index:  in dibspw.php on line 329
[09-Feb-2016 21:43:15 UTC] PHP Notice:  Undefined index:  in dibspw.php on line 331
[09-Feb-2016 21:43:15 UTC] PHP Notice:  Undefined index:  in dibspw.php on line 332
[09-Feb-2016 21:43:15 UTC] PHP Notice:  Undefined index:  in dibspw.php on line 336
[09-Feb-2016 21:43:15 UTC] PHP Notice:  Undefined index:  in dibspw.php on line 337
[09-Feb-2016 21:43:15 UTC] PHP Notice:  Undefined index:  in dibspw.php on line 338
```

The code on lines 326 through 338:
```php
$order_data['shippingfirstname']  = $aAddr[get_option('dibspw_form_first_name_d')];
$order_data['shippinglastname']   = $aAddr[get_option('dibspw_form_last_name_d')];
$order_data['shippingpostalcode'] = $aAddr[get_option('dibspw_form_post_code_d')];
$order_data['shippingpostalplace']= $aAddr[get_option('dibspw_form_city_d')];
//$order_data['shippingaddress2']   = $aAddr[get_option('dibspw_form_address_d')];
$order_data['shippingaddress']    = $aAddr[get_option('dibspw_form_country_d')] . " " .
$aAddr[get_option('dibspw_form_state_d')];

$order_data['billingfirstname']   = $aAddr[get_option('dibspw_form_first_name_b')];
$order_data['billinglastname']    = $aAddr[get_option('dibspw_form_last_name_b')];
$order_data['billingpostalcode']  = $aAddr[get_option('dibspw_form_post_code_b')];
$order_data['billingpostalplace'] = $aAddr[get_option('dibspw_form_city_b')];
$order_data['billingaddress']    = $aAddr[get_option('dibspw_form_address_b')];
//$order_data['billingaddress']     = $aAddr[get_option('dibspw_form_country_b')]. " " .
//                             $aAddr[get_option('dibspw_form_state_b')];

$order_data['billingmobile']      = $aAddr[get_option('dibspw_form_phone_b')];
$order_data['billingemail']       = $aAddr[get_option('dibspw_form_email_b')];
```

This means we can't process any purchases on our site.

Versions:
Wordpress 4.4.2
WP E-commerce 3.11.2

**Comment by maxwhite** [comment]
Hi martisj, thanks for detailed explanation.
Now it is fixed:
https://github.com/DIBS-Payment-Services/Ecommerce/tree/master/dist/DX

**Comment by martisj** [comment]
@maxwhite I see this is the DX version of the gateway. I was using D2 gateway. Forgot to mention that. Does it make a difference?

**Comment by maxwhite** [comment]
@martisj , if you are D2 merchant I would recommend to use this module https://github.com/DIBS-Payment-Services/Ecommerce/tree/master/dist/D2/FlexWin we will stop support D2 PayWin all D2 merchants should use FlexWin

**Comment by martisj** [comment]
@maxwhite Do I have to make any changes to get FlexWin set up?

**Comment by maxwhite** [comment]
@martisj No, it should work

**Comment by martisj** [comment]
But how do I choose that I want to use flexwin instead of paywin?

**Comment by martisj** [comment]
I copied the files from the zip folder into `wp-content/plugins/wp-e-commerce/wpsc-merchants/` and configured the payment options. Now I get a bunch of undefined index errors in `dibs_api/fw/dibs_fw_helpers.php`

```
[08-Mar-2016 23:29:14 UTC] PHP Notice:  Undefined index: id in {}/wp-content/plugins/wp-e-commerce/wpsc-merchants/dibs_api/fw/dibs_fw_helpers.php on line 91
[08-Mar-2016 23:29:14 UTC] PHP Notice:  Undefined index: totalprice in {}/wp-content/plugins/wp-e-commerce/wpsc-merchants/dibs_api/fw/dibs_fw_helpers.php on line 92
[08-Mar-2016 23:29:14 UTC] PHP Notice:  Undefined index: currency in {}/wp-content/plugins/wp-e-commerce/wpsc-merchants/dibs_api/fw/dibs_fw_helpers.php on line 93
[08-Mar-2016 23:29:14 UTC] PHP Notice:  Undefined index: cart in {}/wp-content/plugins/wp-e-commerce/wpsc-merchants/dibs_api/fw/dibs_fw_helpers.php on line 105
[08-Mar-2016 23:29:14 UTC] PHP Notice:  Trying to get property of non-object in {}/wp-content/plugins/wp-e-commerce/wpsc-merchants/dibs_api/fw/dibs_fw_helpers.php on line 105
[08-Mar-2016 23:29:14 UTC] PHP Warning:  Invalid argument supplied for foreach() in {}/wp-content/plugins/wp-e-commerce/wpsc-merchants/dibs_api/fw/dibs_fw_helpers.php on line 105
[08-Mar-2016 23:29:14 UTC] PHP Notice:  Undefined index: total_tax in {}/wp-content/plugins/wp-e-commerce/wpsc-merchants/dibs_api/fw/dibs_fw_helpers.php on line 125
[08-Mar-2016 23:29:14 UTC] PHP Notice:  Undefined index: shipping in {}/wp-content/plugins/wp-e-commerce/wpsc-merchants/dibs_api/fw/dibs_fw_helpers.php on line 140
[08-Mar-2016 23:29:14 UTC] PHP Notice:  Undefined index: shipping in {}/wp-content/plugins/wp-e-commerce/wpsc-merchants/dibs_api/fw/dibs_fw_helpers.php on line 143
[08-Mar-2016 23:29:14 UTC] PHP Notice:  Undefined index: user in {}/wp-content/plugins/wp-e-commerce/wpsc-merchants/dibs_api/fw/dibs_fw_helpers.php on line 161
[08-Mar-2016 23:29:14 UTC] PHP Notice:  Undefined index: additional in {}/wp-content/plugins/wp-e-commerce/wpsc-merchants/dibs_api/fw/dibs_fw_helpers.php on line 251
```

Any ideas?

**Comment by maxwhite** [comment]
Hi @martisj, this issue was fixed please try to reinstall 
https://github.com/DIBS-Payment-Services/Ecommerce/tree/master/dist/D2/FlexWin

**Comment by martisj** [comment]
Yes indeed the issue I was having seems to be fixed, however I am still getting 
```
[13-Mar-2016 20:58:47 UTC] PHP Notice:  Undefined index: billingstate in /plugins/wp-e-commerce/wpsc-includes/purchaselogs.class.php on line 506
[13-Mar-2016 20:58:47 UTC] PHP Notice:  Undefined index: billingcountry in /plugins/wp-e-commerce/wpsc-includes/purchaselogs.class.php on line 522
```

I am only selling to one country so I don't really need the state and country fields. How should I approach this to send the appropriate data with the purchase request?

**Comment by maxwhite** [comment]
Have you disabled Country and State fields ?

**Comment by martisj** [comment]
How do I disable them? I have marked them as "Do not display" and "Required" is turned off.

**Comment by martisj** [comment]
The DIBS callback URL is returning errors as well. Don't really know what that might be. Have no way of telling or debugging this... Heard about something like that before? I am receiving automated emails from DIBS saying `During the authorization of your transaction number: xxxxxxxx,
an error occurred on each of 5 attemps on doing a callback to your server.`

**Comment by maxwhite** [comment]
could you email me maksim.belov@dibs.com.ua and I'll try to help you ?

**Comment by martisj** [comment]
Email address isn't working unfortunately @maxwhite... :sob: 
Any ideas to how I should hack this up?

**Comment by maxwhite** [comment]
sorry, wrong email, this is right:
mabe@dibs.dk
email me here and wrtie your merchantid
